# Generated by Django 5.0.1 on 2026-01-29 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuthorizedID',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(help_text='Unique Student ID allowed to access the system', max_length=50, unique=True)),
                ('is_active', models.BooleanField(default=True, help_text='Uncheck to temporarily disable access for this ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('description', models.CharField(blank=True, help_text='Optional: Name or notes for this ID', max_length=100)),
            ],
            options={
                'verbose_name': 'Authorized Student ID',
                'verbose_name_plural': 'Authorized Student IDs',
            },
        ),
    ]
