# Generated by Django 5.0.1 on 2026-03-31 05:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="TelemetryPulse",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("developer_id", models.CharField(db_index=True, max_length=100)),
                ("timestamp", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("risk_score", models.IntegerField(default=0)),
                ("raw_data", models.TextField(help_text="Full pulse data blob")),
            ],
        ),
        migrations.CreateModel(
            name="CodeSnapshot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("filename", models.CharField(max_length=255)),
                ("content", models.TextField()),
                ("language", models.CharField(max_length=50)),
                (
                    "pulse",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="snapshots",
                        to="authentication.telemetrypulse",
                    ),
                ),
            ],
        ),
    ]
